version: '3.5'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    networks:
      - FileFlow
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fileflow
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - FileFlow
  mailer:
    build: ./microservices/mailer
    container_name: mailer
    restart: always
    volumes:
      - ./microservices/mailer:/app
    networks:
      - FileFlow
    depends_on:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - FileFlow
    command: redis-server --requirepass redis --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - FileFlow
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  FileFlow:
    driver: bridge

volumes:
  redis:
  mysql: