FROM node:20.4.0-slim
RUN apt-get update -y && apt-get install -y openssl build-essential libpq-dev sqlite3

RUN mkdir -p /app
WORKDIR /app

COPY package*.json /app
RUN npm i sqlite3 &&  rm -rf node_modules && npm i && npm rebuild

COPY . /app
RUN npm i -g @nestjs/cli
RUN npm run build

CMD ["npm", "run", "start:prod"]
expose 3000